print("***welcome to our cafe***")
print("plz enter your name")
name=input()
print("Hello "+name)
print("What is your favorite coffee? \n *with milk \n or \n **with out milk ")
my_choose=input()
print("your choose is  "+my_choose)
print("you like it hot or ice?\n")
my_choose2=input()
print("your choose is "+my_choose2)
print("finally,"+name+" your coffee be "+my_choose+" and "+my_choose2)
print("anything else!")
my_choose3=input()
print("Thank you for choosing our caffee")
